### ISSUE TITLE
Screenshot of a caption on The State Of Rollup Interoperability Solutions In 2024

### ISSUE THREAD

**Issue by 0xlynett** [2077-Collective/research.2077.xyz#17]
**Describe the bug**
The post "The State Of Rollup Interoperability Solutions In 2024" has an image which was not properly copied from Mirror, but rather is a screenshot containing the Mirror caption.

https://research.2077.xyz/blog/some-steps-towards-interoperability/

**Expected behavior**
The images would be copied over or screenshotted without the caption.

**Screenshots**

![image](https://github.com/user-attachments/assets/3bb9b181-44b4-4c22-8dfd-c6bd12f9e925)

**Comment by 2077collective** [comment]
Fixed. Thanks Oxlynett
